name: CI/CD

on:
  push:
    branches: [ "ci/github-action" ]

jobs:
  CI:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo DEBUG=${{ secrets.DJANGO_DEBUG }} >> .env
          echo API_URL=${{ secrets.DJANGO_API_URL }} >> .env
          echo WEB_URL=${{ secrets.DJANGO_WEB_URL }} >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          build-args: |
            ENV=${{ secrets.ENV }}
            DRIVER_CLASS_NAME=${{ secrets.DRIVER_CLASS_NAME }}
            JDBC_URL=${{ secrets.JDBC_URL }} 
            JDBC_USER=${{ secrets.JDBC_USER }} 
            JDBC_PASSWORD=${{ secrets.JDBC_PASSWORD }}

  CD:
    needs: [ CI ]
    runs-on: ubuntu-20.04

    steps:
      - name: Run container
        run: |
          docker stop jsp-cafe
          docker rm jsp-cafe
          docker run -d -p 8080:8080 --name jsp-cafe ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest